//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.SqlServer;
    using SqlProviderServices = System.Data.Entity.SqlServer.SqlProviderServices;/// <summary>
    /// //////////////////////////////////////////////////////////////////
    /// </summary>


    public partial class GangrenaShopEntities : DbContext
    {

        public GangrenaShopEntities()
            : base("name=GangrenaShopEntities")
        {

        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Categorias> Categorias { get; set; }
        public virtual DbSet<Clasificaciones> Clasificaciones { get; set; }
        public virtual DbSet<Clientes> Clientes { get; set; }
        public virtual DbSet<Empleados> Empleados { get; set; }
        public virtual DbSet<Productos> Productos { get; set; }
        public virtual DbSet<Proveedores> Proveedores { get; set; }
        public virtual DbSet<Tipo_pago> Tipo_pago { get; set; }
        public virtual DbSet<Ventas> Ventas { get; set; }
        public virtual DbSet<Ventas_conceptos> Ventas_conceptos { get; set; }
    }
}
