//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class Productos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Productos()
        {
            this.Ventas_conceptos = new HashSet<Ventas_conceptos>();
        }
    
        public int id_producto { get; set; }
        public string nombre { get; set; }
        public string descripcion { get; set; }
        public Nullable<decimal> precio_compra { get; set; }
        public Nullable<decimal> precio_venta { get; set; }
        public int existencias { get; set; }
        public int id_categoria { get; set; }
        public int id_clasificacion { get; set; }
        public int id_proveedor { get; set; }
    
        public virtual Categorias Categorias { get; set; }
        public virtual Clasificaciones Clasificaciones { get; set; }
        public virtual Proveedores Proveedores { get; set; }
        [JsonIgnore]
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ventas_conceptos> Ventas_conceptos { get; set; }
    }
}
